
-- Folosim CASCADE CONSTRAINTS pentru a ignora ordinea dependentelor la stergere
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOGS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE REMEDIATION_TICKETS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DETECTED_VULNS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ASSETS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SCAN_SESSIONS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE VULNERABILITY_DB CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SECURITY_TEAMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE APP_USERS CASCADE CONSTRAINTS';
END;

   -- Optional: Stergem si pachetele/procedurile pentru a le recrea
BEGIN
   EXECUTE IMMEDIATE 'DROP PACKAGE PKG_VULNSIGHT';
   EXECUTE IMMEDIATE 'DROP PROCEDURE SP_RESOLVE_TICKET';
EXCEPTION
   WHEN OTHERS THEN
      -- Ignoram eroarea daca tabelele nu exista (la prima rulare)
      IF SQLCODE != -942 AND SQLCODE != -4043 THEN 
         RAISE; 
      END IF;
END;
/