
-- 1. CLEANUP (Stergem tabelele vechi daca exista pentru a putea rerula scriptul)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE REMEDIATION_TICKETS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DETECTED_VULNS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ASSETS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SCAN_SESSIONS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE VULNERABILITY_DB CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SECURITY_TEAMS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE APP_USERS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 2. CREARE TABELE
-- Tabel 1: Departamente
CREATE TABLE DEPARTMENTS (
    Dept_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Dept_Name VARCHAR2(100) NOT NULL,
    Budget NUMBER(12, 2) DEFAULT 0, -- 12 cifre, 2 zecimale
    Risk_Weight NUMBER(3, 1) DEFAULT 1.0 -- Pondere risc (ex: 1.5 pt IT, 0.8 pt HR)
);

-- Tabel 2: Echipe de Securitate
CREATE TABLE SECURITY_TEAMS (
    Team_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Team_Name VARCHAR2(100) NOT NULL UNIQUE,
    Team_Lead VARCHAR2(100),
    Specialization VARCHAR2(50) CHECK (Specialization IN ('Infrastructure', 'AppSec', 'Compliance', 'Network'))
);

-- Tabel 3: Baza de date de Vulnerabilități (Catalog CVE)
CREATE TABLE VULNERABILITY_DB (
    CVE_ID VARCHAR2(20) PRIMARY KEY, -- Ex: CVE-2024-1234
    Description VARCHAR2(4000),
    Base_Score NUMBER(3, 1) NOT NULL CHECK (Base_Score BETWEEN 0 AND 10),
    Severity VARCHAR2(20) CHECK (Severity IN ('Low', 'Medium', 'High', 'Critical')),
    Published_Date DATE DEFAULT SYSDATE
);

-- Tabel 4: Sesiuni de Scanare (Log-uri)
CREATE TABLE SCAN_SESSIONS (
    Session_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Scan_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Tool_Used VARCHAR2(50) NOT NULL, -- Ex: Nessus, Qualys
    Scanner_Operator VARCHAR2(100)
);

-- Tabel 5: Utilizatori Aplicatie (BONUS - Tabelul 8 pentru siguranta)
CREATE TABLE APP_USERS (
    User_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) NOT NULL UNIQUE,
    Password_Hash VARCHAR2(255) NOT NULL,
    Role VARCHAR2(20) CHECK (Role IN ('Admin', 'CISO', 'Viewer', 'Auditor')),
    Created_At DATE DEFAULT SYSDATE
);

-- 3. CREARE TABELE OPERATIONALE
-- Tabel 6: Active IT (Assets)
CREATE TABLE ASSETS (
    Asset_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Hostname VARCHAR2(100) NOT NULL,
    IP_Address VARCHAR2(45), -- Suporta si IPv6
    OS_Type VARCHAR2(50),
    Is_Critical NUMBER(1,0) DEFAULT 0 CHECK (Is_Critical IN (0, 1)), -- Boolean (0/1)
    Dept_ID NUMBER REFERENCES DEPARTMENTS(Dept_ID),
    Team_ID NUMBER REFERENCES SECURITY_TEAMS(Team_ID) -- Echipa responsabila de acest asset
);

-- Tabel 7: Vulnerabilitati Detectate (Link-ul masiv Many-to-Many)
CREATE TABLE DETECTED_VULNS (
    Det_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Asset_ID NUMBER NOT NULL REFERENCES ASSETS(Asset_ID) ON DELETE CASCADE,
    CVE_ID VARCHAR2(20) NOT NULL REFERENCES VULNERABILITY_DB(CVE_ID),
    Session_ID NUMBER REFERENCES SCAN_SESSIONS(Session_ID),
    Status VARCHAR2(20) DEFAULT 'Open' CHECK (Status IN ('Open', 'Fixed', 'False Positive', 'Risk Accepted')),
    Date_Detected DATE DEFAULT SYSDATE,
    Risk_Accepted NUMBER(1,0) DEFAULT 0 CHECK (Risk_Accepted IN (0, 1)),
    
    -- Unicitate: Aceeasi vulnerabilitate pe acelasi asset nu ar trebui sa apara de 2 ori ca 'Open'
    CONSTRAINT UQ_Asset_Vuln UNIQUE (Asset_ID, CVE_ID, Session_ID)
);

-- Tabel 8: Tichete de Remediere (Procesul de patching)
CREATE TABLE REMEDIATION_TICKETS (
    Ticket_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Det_ID NUMBER NOT NULL REFERENCES DETECTED_VULNS(Det_ID) ON DELETE CASCADE,
    Assigned_Team_ID NUMBER REFERENCES SECURITY_TEAMS(Team_ID),
    Priority VARCHAR2(10) CHECK (Priority IN ('P1', 'P2', 'P3', 'P4')),
    Created_Date DATE DEFAULT SYSDATE,
    Due_Date DATE,
    Resolved_Date DATE,
    Resolution_Notes VARCHAR2(1000),
    
    -- Constraint logic: Data rezolvarii nu poate fi inainte de data crearii
    CONSTRAINT CHK_Dates CHECK (Resolved_Date >= Created_Date)
);

-- Tabel de audit pentru a urmari cine si ce a modificat
CREATE TABLE AUDIT_LOGS (
    Log_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Action_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    User_App VARCHAR2(50), -- Cine a facut modificarea
    Target_Table VARCHAR2(50),
    Target_ID NUMBER,
    Old_Value VARCHAR2(100),
    New_Value VARCHAR2(100),
    Message VARCHAR2(500)
);

SELECT 'Structura bazei de date VulnSight a fost creata cu succes!' AS Status FROM DUAL;